production:
  adapter: postgresql
  encoding: unicode
  database: app_development
  pool: 2
  username: pizza_user
  password: pizza_pw

development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  pool: 2
  username: pizza_user
  password: pizza_pw