production:
  adapter: postgresql
  encoding: unicode
  database: database
  pool: 2
  username: username
  password: password

development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  pool: 2
